version: '3.8'

services:
    node:
        container_name: twilingway-we-exist
        build: .
        image: twilingway/we-exist:0.0.16
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_EXP=${JWT_EXP}
            - JWT_SECRET=${JWT_SECRET}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - YANDEX_APP_ID=${YANDEX_APP_ID}
            - YANDEX_APP_SECRET=${YANDEX_APP_SECRET}
            - NODE_ENV=${NODE_ENV}
        env_file:
            - .env
        ports:
            - 3003:3003
